"""Turn a scheduled tick into ingested data.

One entry point per job:

  * ``run_forecast_cycle``      - pull an operational GEFS cycle, ingest, re-score.
  * ``run_observation_refresh`` - pull observations for a tier, ingest, maybe retrain.
  * ``run_due_work``            - what the scheduler calls: whichever of the above is due.
  * ``backfill_cycles``         - pull N past cycles, oldest first, resumable.

Every attempt writes an ``IngestRun`` row, including the ones that skip or fail, so
``/api/ingest/status`` can show real feed health rather than implying data is current.

Two things this deliberately does NOT do:

  * It never retrains on a forecast pull. A forecast that has not verified yet carries no
    label to learn from; only newly-final observations trigger training.
  * It never invents a mapping. Live files are generated by this codebase, so their column
    mapping is passed explicitly rather than left to the schema mapper's heuristics - an
    unattended job must not depend on fuzzy matching, and a mis-mapped pressure column
    would be silently wrong rather than loudly broken.
"""

from __future__ import annotations

import logging
import threading
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import Optional

from sqlalchemy.orm import Session

from app.config import settings
from app.db.base import get_session, resolve_path
from app.db.models import IngestRun
from app.ingestion.pipeline import ingest_upload
from app.live import gefs, observations
from app.ml import inference
from app.realtime.broadcaster import emit
from app.realtime.events import EventType
from app.storage import parquet_store

log = logging.getLogger("forecastguard.live.orchestrator")

LIVE_DIR = resolve_path(settings.data_dir) / "live"

# Guards a single machine against two ingest jobs overlapping - a slow cycle pull and the
# next scheduled tick, or a manual "refresh now" landing mid-run.
_ingest_lock = threading.Lock()

# --------------------------------------------------------------------------------------
# Explicit column mappings.
#
# These mirror exactly how the 2019 training files were mapped, verified against the
# canonical store. The pressure pair is the one that matters: BOTH files carry mslp_hpa and
# psfc_hpa, and only mslp_hpa becomes pressure_hpa. Surface pressure is dominated by
# station elevation (Leh sits near 684 hPa), so mixing it into the same canonical variable
# as mean-sea-level pressure would make the pressure model meaningless.
# --------------------------------------------------------------------------------------

FORECAST_MAPPINGS = [
    {"source_column": "t2m_c", "variable": "temperature_c", "value_type": "forecast"},
    {"source_column": "rh2m_pct", "variable": "humidity_pct", "value_type": "forecast"},
    {"source_column": "apcp_mm", "variable": "rainfall_mm", "value_type": "forecast"},
    {"source_column": "mslp_hpa", "variable": "pressure_hpa", "value_type": "forecast"},
    {"source_column": "pwat_kgm2", "variable": "atmospheric_moisture_kgm2", "value_type": "forecast"},
    {"source_column": "soilw_vol_pct", "variable": "soil_moisture_pct", "value_type": "forecast"},
    {"source_column": "wspd10m_ms", "variable": "wind_speed_ms", "value_type": "forecast"},
    {"source_column": "wdir10m_deg", "variable": "wind_direction_deg", "value_type": "forecast"},
    {"source_column": "psfc_hpa", "role": "unmapped"},
]

OBSERVATION_MAPPINGS = [
    {"source_column": "t2m_c", "variable": "temperature_c", "value_type": "observed"},
    {"source_column": "rh2m_pct", "variable": "humidity_pct", "value_type": "observed"},
    {"source_column": "precip_mm", "variable": "rainfall_mm", "value_type": "observed"},
    {"source_column": "mslp_hpa", "variable": "pressure_hpa", "value_type": "observed"},
    {"source_column": "pwat_kgm2", "variable": "atmospheric_moisture_kgm2", "value_type": "observed"},
    {"source_column": "soil_moisture_pct", "variable": "soil_moisture_pct", "value_type": "observed"},
    {"source_column": "wspd10m_ms", "variable": "wind_speed_ms", "value_type": "observed"},
    {"source_column": "wdir10m_deg", "variable": "wind_direction_deg", "value_type": "observed"},
    {"source_column": "psfc_hpa", "role": "unmapped"},
    # `source` is free-text provenance, but the mapper reads it as a per-row value_type
    # discriminator - and a row-level value_type overrides every column's confirmed one.
    # Excluding it explicitly is what keeps these rows labelled "observed".
    {"source_column": "source", "role": "unmapped"},
]


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _start_run(session: Session, kind: str, target: str, trigger: str) -> IngestRun:
    run = IngestRun(kind=kind, target=target, trigger=trigger, status="running")
    session.add(run)
    session.commit()
    session.refresh(run)
    return run


def _finish_run(session: Session, run: IngestRun, status: str, **fields) -> None:
    run.status = status
    run.finished_at = _now()
    for k, v in fields.items():
        setattr(run, k, v)
    session.commit()


def cycle_target(init: date, cycle_hour: str) -> str:
    return f"{init.isoformat()} {cycle_hour}"


def cycle_already_ingested(session: Session, init: date, cycle_hour: str) -> bool:
    """Has this exact cycle already been ingested?

    Keyed on (date, hour) rather than the canonical store's ``init_date``, because a date
    alone cannot distinguish the 00Z run from the 06Z one - and partitions are per
    batch_id, so a repeat pull would add a duplicate partition rather than replace it.
    """
    return session.query(IngestRun).filter(
        IngestRun.kind == "forecast",
        IngestRun.target == cycle_target(init, cycle_hour),
        IngestRun.status == "complete",
    ).first() is not None


# --------------------------------------------------------------------------------------
# jobs
# --------------------------------------------------------------------------------------

def run_forecast_cycle(
    init: Optional[date] = None,
    cycle_hour: Optional[str] = None,
    trigger: str = "schedule",
    force: bool = False,
) -> dict:
    """Fetch, ingest and re-score one operational GEFS cycle."""
    if init is None or cycle_hour is None:
        init, cycle_hour = gefs.latest_expected_cycle(
            lag_hours=settings.live_gefs_publish_lag_hours,
            cycles=settings.gefs_cycle_list,
        )
    target = cycle_target(init, cycle_hour)

    with get_session() as session:
        if not force and cycle_already_ingested(session, init, cycle_hour):
            log.info("cycle %s already ingested; skipping", target)
            return {"status": "skipped", "target": target, "reason": "already ingested"}
        run = _start_run(session, "forecast", target, trigger)
        run_id = run.id

    try:
        members = settings.gefs_member_list
        frame, report = gefs.fetch_cycle(
            init, cycle_hour, members=members,
            workers=settings.live_download_workers,
        )
        path = gefs.write_cycle_csv(frame, init, cycle_hour, LIVE_DIR)

        with get_session() as session:
            result = ingest_upload(session, path, path.name,
                                   confirmed_mappings=FORECAST_MAPPINGS)
            detail = (
                f"transport={report.transport} steps={report.steps_fetched}/"
                f"{report.steps_expected} {report.bytes_downloaded/1048576:.1f}MB "
                f"in {report.seconds:.0f}s; members={','.join(members)}; "
                f"variables={','.join(result.canonical_variables_found)}"
            )
            if report.steps_recovered:
                detail += f"; recovered_from_s3={report.steps_recovered}"
            if report.missing_steps:
                detail += f"; missing_steps={len(report.missing_steps)}"
            if report.undersampled:
                detail += f"; undersampled={len(report.undersampled)}"
            run = session.get(IngestRun, run_id)
            _finish_run(session, run, "complete",
                        upload_batch_id=result.batch_id,
                        rows_ingested=result.row_count_ingested,
                        detail=detail)

        # A new cycle changes what "latest" means, so the scoring cache must go. No
        # retrain: this forecast has not verified against anything yet.
        inference.invalidate_caches()
        emit(EventType.UPLOAD_RECEIVED, filename=path.name, source="live-gefs")
        emit(EventType.NEW_ALERT, cycle=target, rows=result.row_count_ingested)
        log.info("ingested cycle %s: %s rows", target, result.row_count_ingested)
        return {
            "status": "complete", "target": target,
            "rows_ingested": result.row_count_ingested,
            "batch_id": result.batch_id, "transport": report.transport,
            "steps": f"{report.steps_fetched}/{report.steps_expected}",
            "missing_steps": report.missing_steps,
            "undersampled": report.undersampled[:20],
            # The lists above are truncated for readability, so callers deciding whether a
            # cycle is fit to publish need the totals separately. `undersampled_sums` is
            # counted apart because a short accumulation understates rainfall rather than
            # just adding noise - see FetchReport.undersampled_sums.
            "steps_fetched": report.steps_fetched,
            "steps_expected": report.steps_expected,
            "steps_recovered": report.steps_recovered,
            "step_completeness": round(report.step_completeness, 4),
            "undersampled_count": len(report.undersampled),
            "undersampled_sum_count": len(report.undersampled_sums),
            "seconds": round(report.seconds, 1),
        }

    except gefs.CycleUnavailable as exc:
        with get_session() as session:
            _finish_run(session, session.get(IngestRun, run_id), "skipped", detail=str(exc))
        log.info("cycle %s not available: %s", target, exc)
        return {"status": "skipped", "target": target, "reason": str(exc)}
    except Exception as exc:  # noqa: BLE001
        with get_session() as session:
            _finish_run(session, session.get(IngestRun, run_id), "failed",
                        error=f"{type(exc).__name__}: {exc}")
        log.exception("cycle %s failed", target)
        return {"status": "failed", "target": target, "error": str(exc)}


def run_observation_refresh(
    tier: str = "final",
    days_back: Optional[int] = None,
    trigger: str = "schedule",
    retrain: Optional[bool] = None,
) -> dict:
    """Pull one observation tier and ingest it.

    Only the final tier can trigger training - provisional rows are excluded from the
    training read entirely (see parquet_store.read_dataset(exclude_provisional=True)).
    """
    if days_back is None:
        days_back = (settings.live_obs_final_days if tier == "final"
                     else settings.live_obs_provisional_days)
    start, end = observations.default_window(days_back, tier)
    kind = f"observations_{tier}"
    target = f"{start.isoformat()}..{end.isoformat()}"

    with get_session() as session:
        run = _start_run(session, kind, target, trigger)
        run_id = run.id

    try:
        frame, report = observations.fetch_observations(start, end, tier=tier)
        if frame.empty:
            with get_session() as session:
                _finish_run(session, session.get(IngestRun, run_id), "skipped",
                            detail=f"no observations returned for {target}")
            return {"status": "skipped", "target": target, "reason": "no rows returned"}

        path = observations.write_observations_csv(frame, tier, start, end, LIVE_DIR)
        with get_session() as session:
            result = ingest_upload(session, path, path.name,
                                   confirmed_mappings=OBSERVATION_MAPPINGS,
                                   verification_status=tier)
            detail = (f"tier={tier} cities={report.cities} rows={result.row_count_ingested} "
                      f"in {report.seconds:.0f}s")
            if report.failures:
                detail += f"; failed_cities={','.join(report.failures)}"
            _finish_run(session, session.get(IngestRun, run_id), "complete",
                        upload_batch_id=result.batch_id,
                        rows_ingested=result.row_count_ingested,
                        detail=detail)

        inference.invalidate_caches()
        emit(EventType.UPLOAD_RECEIVED, filename=path.name, source=f"live-obs-{tier}")

        should_retrain = (
            retrain if retrain is not None
            else (tier == "final"
                  and result.row_count_ingested >= settings.live_retrain_min_new_rows)
        )
        out = {"status": "complete", "target": target, "tier": tier,
               "rows_ingested": result.row_count_ingested,
               "batch_id": result.batch_id, "retrain_triggered": bool(should_retrain)}

        if should_retrain:
            from app.services.upload_service import run_retrain
            threading.Thread(target=run_retrain, args=(result.batch_id,),
                             name="live-retrain", daemon=True).start()
        return out

    except Exception as exc:  # noqa: BLE001
        with get_session() as session:
            _finish_run(session, session.get(IngestRun, run_id), "failed",
                        error=f"{type(exc).__name__}: {exc}")
        log.exception("observation refresh (%s) failed", tier)
        return {"status": "failed", "target": target, "error": str(exc)}


def run_due_work(trigger: str = "schedule") -> dict:
    """One scheduler tick: the newest unfetched cycle, plus observations when due.

    Serialised behind a lock; a tick that arrives while another is still working returns
    immediately rather than queueing up overlapping downloads.
    """
    if not _ingest_lock.acquire(blocking=False):
        log.info("ingest already running; this tick does nothing")
        return {"status": "busy"}
    try:
        out: dict = {"forecast": run_forecast_cycle(trigger=trigger)}

        with get_session() as session:
            out["provisional"] = (
                run_observation_refresh("provisional", trigger=trigger)
                if _due(session, "observations_provisional", hours=6) else {"status": "not_due"}
            )
            final_due = _due(session, "observations_final", hours=24)
        # Kept outside the session above so the long HTTP work does not hold it open.
        out["final"] = (run_observation_refresh("final", trigger=trigger)
                        if final_due else {"status": "not_due"})
        return out
    finally:
        _ingest_lock.release()


def _due(session: Session, kind: str, hours: float) -> bool:
    last = (session.query(IngestRun)
            .filter(IngestRun.kind == kind, IngestRun.status == "complete")
            .order_by(IngestRun.started_at.desc()).first())
    if last is None or last.finished_at is None:
        return True
    finished = last.finished_at
    if finished.tzinfo is None:            # SQLite hands back naive datetimes
        finished = finished.replace(tzinfo=timezone.utc)
    return (_now() - finished) >= timedelta(hours=hours)


def backfill_cycles(count: int, stride_hours: int = 24, trigger: str = "backfill") -> list:
    """Pull `count` past cycles, oldest first so an interrupted run leaves a contiguous
    recent history rather than isolated islands. Already-ingested cycles are skipped, so
    re-running resumes where it stopped."""
    wanted = gefs.recent_cycles(
        count, lag_hours=settings.live_gefs_publish_lag_hours,
        cycles=settings.gefs_cycle_list, stride_hours=stride_hours,
    )
    results = []
    for init, hh in reversed(wanted):      # oldest first
        results.append(run_forecast_cycle(init, hh, trigger=trigger))
    return results


def _run_row(r) -> dict:
    """One IngestRun as plain JSON. Read inside the session - the ORM instance is detached
    once it closes, and touching it afterwards raises DetachedInstanceError."""
    return {
        "id": r.id, "kind": r.kind, "target": r.target, "status": r.status,
        "trigger": r.trigger, "rows_ingested": r.rows_ingested,
        "started_at": r.started_at.isoformat() if r.started_at else None,
        "finished_at": r.finished_at.isoformat() if r.finished_at else None,
        "seconds": (round((r.finished_at - r.started_at).total_seconds(), 1)
                    if r.started_at and r.finished_at else None),
        "detail": r.detail, "error": r.error,
    }


def recent_runs(limit: int = 25) -> list:
    """The pipeline's own history, newest first - every attempt, not only the ones that
    worked.

    Skipped and failed runs are included deliberately. A cycle that NOAA served too
    incompletely to trust is refused rather than published, and that refusal is the
    project's argument in miniature: the alternative is a forecast whose rainfall is
    silently halved. A log that showed only successes would be the same kind of
    convenient fiction this system exists to avoid.
    """
    with get_session() as session:
        rows = (session.query(IngestRun)
                .order_by(IngestRun.started_at.desc())
                .limit(max(1, min(int(limit), 200))).all())
        return [_run_row(r) for r in rows]


def feed_status() -> dict:
    """What /api/ingest/status serves: real freshness, never an implied 'current'."""
    with get_session() as session:
        def last(kind: str):
            r = (session.query(IngestRun)
                 .filter(IngestRun.kind == kind)
                 .order_by(IngestRun.started_at.desc()).first())
            if r is None:
                return None
            return {"target": r.target, "status": r.status, "trigger": r.trigger,
                    "rows_ingested": r.rows_ingested,
                    "started_at": r.started_at.isoformat() if r.started_at else None,
                    "finished_at": r.finished_at.isoformat() if r.finished_at else None,
                    "detail": r.detail, "error": r.error}

        # Newest cycle by target, NOT by when it was fetched: a backfill runs oldest-first,
        # so the most recently started run is not the most recent forecast. The dashboard
        # scores the newest cycle in the store, and this line has to name that same one.
        # The target format "YYYY-MM-DD HH" sorts chronologically as text.
        #
        # Read the attribute inside the session: the ORM instance is detached once the
        # session closes, and touching it afterwards raises DetachedInstanceError.
        completed = (session.query(IngestRun.target)
                     .filter(IngestRun.kind == "forecast", IngestRun.status == "complete")
                     .order_by(IngestRun.target.desc()).first())
        last_cycle = completed[0] if completed else None

    return {
        "enabled": settings.live_ingest_enabled,
        "cycles_watched": settings.gefs_cycle_list,
        "members": settings.gefs_member_list,
        "last_forecast": last("forecast"),
        "last_observations_provisional": last("observations_provisional"),
        "last_observations_final": last("observations_final"),
        "last_cycle_ingested": last_cycle,
        "latest_forecast_init_date": (
            d.isoformat() if (d := parquet_store.latest_forecast_init_date()) else None
        ),
    }
