"""District registry and grid-to-district aggregation.

Sanket's region unit is the district, not the state. Two things live here:

* the **registry** - 666 districts with a stable ``region_id``, their state, centroid and
  bounding box - loaded from ``data/geo/india_districts.json``;
* the **aggregator** - turns a gridded field (GEFS or ERA5, 0.25 deg) into one
  area-weighted value per district.

Both files are generated by ``scripts/build_district_geo.py``; that script's docstring
records where the boundaries came from and which corrections were applied to them.

Why area-weighted and not nearest-point
--------------------------------------
The previous design read one city point per state, so a state's forecast was its capital's
forecast. Sampling a district's nearest grid point would repeat that mistake at smaller
scale, and would leave the ten smallest districts - Kolkata, Hyderabad, the Puducherry
enclaves, Lakshadweep - with no grid centre inside them at all. Weighting by the area each
0.25 deg cell contributes gives every district a defined value and gives large ones a
genuine spatial mean.
"""
from __future__ import annotations

import functools
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

from app.config import settings
from app.db.base import resolve_path

REGISTRY_FILENAME = "india_districts.json"
WEIGHTS_FILENAME = "district_grid_weights.parquet"
GEOJSON_FILENAME = "india_districts.geojson"

# Weights were built on a 0.25 deg grid; a lat/lon is matched to a cell by rounding to
# that grid, so a feed whose points sit on the same grid needs no interpolation.
GRID_DEG = 0.25
_QUANT = round(1 / GRID_DEG)


def geo_dir() -> Path:
    return resolve_path(settings.geo_dir)


@dataclass(frozen=True)
class DistrictRecord:
    region_id: str
    region_name: str
    state_id: str
    state_name: str
    centroid_lat: float
    centroid_lon: float

    @property
    def display_name(self) -> str:
        """Districts are not uniquely named to a reader: Delhi, Karnataka and Tamil Nadu
        all have a 'North'. Anything user-facing needs the state alongside - except where
        the district and the state share a name, because "Delhi, Delhi" and
        "Lakshadweep, Lakshadweep" read as a bug rather than as a location."""
        if self.region_name.lower() == self.state_name.lower():
            return self.region_name
        return f"{self.region_name}, {self.state_name}"


def _norm_lon(lon: float) -> float:
    """GEFS publishes longitudes on 0..360, the boundaries are on -180..180."""
    lon = float(lon) % 360.0
    return lon - 360.0 if lon > 180.0 else lon


def _cell_key(lat: float, lon: float) -> tuple[int, int]:
    """A grid cell as integer quarter-degrees, so float noise cannot miss a match."""
    return (int(round(float(lat) * _QUANT)), int(round(_norm_lon(lon) * _QUANT)))


@functools.lru_cache(maxsize=1)
def load_registry() -> tuple[DistrictRecord, ...]:
    path = geo_dir() / REGISTRY_FILENAME
    raw = json.loads(Path(path).read_text())
    return tuple(
        DistrictRecord(
            region_id=r["region_id"],
            region_name=r["region_name"],
            state_id=r["state_id"],
            state_name=r["state_name"],
            centroid_lat=float(r["centroid"][0]),
            centroid_lon=float(r["centroid"][1]),
        )
        for r in raw
    )


@functools.lru_cache(maxsize=1)
def _by_id() -> dict[str, DistrictRecord]:
    return {d.region_id: d for d in load_registry()}


def resolve_by_id(region_id: str | None) -> DistrictRecord | None:
    return _by_id().get(region_id) if region_id else None


@functools.lru_cache(maxsize=1)
def _by_name() -> dict[str, list[DistrictRecord]]:
    out: dict[str, list[DistrictRecord]] = {}
    for d in load_registry():
        for key in {d.region_name.lower(), d.display_name.lower()}:
            out.setdefault(key, []).append(d)
    return out


def resolve_by_name(name: str | None, state: str | None = None) -> DistrictRecord | None:
    """Districts share names across states, so an unqualified name that matches more than
    one district resolves to nothing rather than to an arbitrary pick."""
    if not name:
        return None
    hits = _by_name().get(name.strip().lower(), [])
    if state:
        want = state.strip().lower()
        hits = [d for d in hits
                if want in (d.state_name.lower(), d.state_id.lower())] or hits
    return hits[0] if len(hits) == 1 else None


class DistrictGridAggregator:
    """Area-weighted mean of a 0.25 deg field over each district.

    Built once and reused: the weight table is ~10k rows and turning it into index arrays
    on every GRIB message would dominate the cost of reading one.
    """

    def __init__(self, weights_path: Path | None = None):
        path = Path(weights_path or (geo_dir() / WEIGHTS_FILENAME))
        w = pd.read_parquet(path)
        self.region_ids: list[str] = sorted(w["region_id"].unique())
        region_pos = {r: i for i, r in enumerate(self.region_ids)}

        cells = w[["lat", "lon"]].drop_duplicates().itertuples(index=False)
        self._cell_pos = {_cell_key(c.lat, c.lon): i for i, c in enumerate(cells)}

        self._rows = w["region_id"].map(region_pos).to_numpy(dtype=np.int32)
        self._cell_keys = [_cell_key(la, lo) for la, lo in zip(w["lat"], w["lon"])]
        self._w = w["weight"].to_numpy(dtype=np.float64)
        self._n_cells = len(self._cell_pos)

    def prepare(self, lats, lons) -> np.ndarray:
        """Index of every weight row into a field ravelled on this grid; -1 where the
        grid does not carry that cell.

        Built once per grid and reused. The fetch aggregates 400 fields per cycle - eight
        variables, five members, ten lead days - and resolving each cell through a dict on
        every one of them costs 8 million Python-level lookups per cycle. With the index
        prepared, each aggregation is a gather and two bincounts.
        """
        lats = np.asarray(lats, dtype=np.float64).ravel()
        lons = np.asarray(lons, dtype=np.float64).ravel()
        if len(lats) != len(lons):
            raise ValueError("lats and lons must be the same length")
        pos = {_cell_key(la, lo): i for i, (la, lo) in enumerate(zip(lats, lons))}
        return np.array([pos.get(k, -1) for k in self._cell_keys], dtype=np.int64)

    def aggregate_prepared(self, index: np.ndarray, values) -> pd.Series:
        """Aggregate a field ravelled on the grid ``index`` was prepared for."""
        values = np.asarray(values, dtype=np.float64).ravel()
        cell_vals = np.where(index >= 0, values[np.clip(index, 0, None)], np.nan)

        valid = ~np.isnan(cell_vals)
        n = len(self.region_ids)
        num = np.bincount(self._rows[valid],
                          weights=(self._w[valid] * cell_vals[valid]), minlength=n)
        den = np.bincount(self._rows[valid], weights=self._w[valid], minlength=n)
        with np.errstate(invalid="ignore", divide="ignore"):
            out = np.where(den > 0, num / den, np.nan)
        return pd.Series(out, index=pd.Index(self.region_ids, name="region_id"))

    def aggregate(self, lats, lons, values) -> pd.Series:
        """Flat arrays of cell latitude, longitude and value -> value per ``region_id``.

        Cells the weight table does not know are ignored (the caller may hand over a
        bounding box wider than India). ``NaN`` cells - a land variable over sea, a gap in
        a feed - are dropped and the remaining weights renormalised over what is left, so
        a coastal district is not turned into ``NaN`` by the sea cells it overlaps. A
        district with no valid cell at all returns ``NaN``, never a fabricated number.
        """
        values = np.asarray(values, dtype=np.float64).ravel()
        if not (len(np.asarray(lats).ravel()) == len(np.asarray(lons).ravel())
                == len(values)):
            raise ValueError("lats, lons and values must be the same length")
        return self.aggregate_prepared(self.prepare(lats, lons), values)


@functools.lru_cache(maxsize=1)
def get_aggregator() -> DistrictGridAggregator:
    return DistrictGridAggregator()
